### PR TITLE
USBD_CDC: Allow setting the CDC string descriptor

### PR DESCRIPTION
**Pull request by jepler**

### CODE REVIEW

**Comment by jepler** [comment]
I'm having trouble figuring out why there are two separate implementations of "CDC", one in `src/arduino` and one in `src/arduino/cdc` @hathach

**Comment by hathach** [comment]
> I'm having trouble figuring out why there are two separate implementations of "CDC", one in `src/arduino` and one in `src/arduino/cdc` @hathach

one is host, one is device, the naming is easy to miss. The cdc device reside in the 'arduino/' is for compatible(historical) reason with multiple bsp/core version.

**Comment by jepler** [comment]
I think part of the reason it's failing is it's mixing BSP headers with this library cpp files. This is not easy like I'd goes

**Comment by jepler** [comment]
I opened this PR while investigating various ways to allow host software like greaseweazle and fluxengine to automatically detect when an Adafruit Floppsy is loaded with a compatible firmware. Otherwise, the port has to be specified each time the software is run.

the greaseweazle author incorporated a change to check the product string, and fluxengine right now uses a USB library that can't get either the product string or the CDC string so it's a moot point and I don't think this will be needed right now.

**Pull request closed without merging**
