### PR TITLE
Update tinyusb to commit 48f4d8b7f7eda7ee4046c1c6cd9be2b5c0d81603

### PR DESCRIPTION
**Pull request by hathach**
- update tinyusb to commit https://github.com/hathach/tinyusb/commit/48f4d8b7f7eda7ee4046c1c6cd9be2b5c0d81603 , which adds support for host cdc

### CODE REVIEW

**Comment by earlephilhower** [comment]
Will there be a new release soon?  I'd like to pull this into the Arduino-Pico tree...

**Comment by hathach** [comment]
@earlephilhower it probably needs a day or two, this update mostly for adding host cdc support. I still need to add a few class support for that as well.

**Comment by hathach** [comment]
@earlephilhower https://github.com/adafruit/Adafruit_TinyUSB_Arduino/releases/tag/1.17.0 is just released

**Comment by earlephilhower** [comment]
Thanks, just added the PR.

**Pull request merged**
