### PR TITLE
MIDI: Add raw USB packet interface

### PR DESCRIPTION
**Pull request by kaysievers**
Add methods to send and retrieve a full 4-byte USB MIDI packet:
  bool send(const MIDIPacket* packet);
  bool receive(MIDIPacket* packet);

Add example 'midi_virtual_ports.ino':
  The sketch is enumerated as USB MIDI device which shows up at the
  host as a single MIDI interface with 3 virtual ports/wires.

  Every port continuously sends out notes:
    Port 1, channel 1: monochord (single tone)
    port 2, channel 4: dichord (two tones)
    port 3, channel 8: trichord (three tones)

  Notes received on the ports let the built-in LED blink one, two,
  or three times.

  MIDI.h is a small wrapper around the USB MIDI packet interface. It
  does not require any external MIDI library.

### CODE REVIEW

**Comment by hathach** [comment]
hmm, `MIDI.cpp` this is implementation of an MIDI library. Do you know of any 3rd party library that we can use with. If we cannot find one, we may just use the raw send()/receive() API for the example. Since I have no intention nor the knowledge to maintain a MIDI implementation within this USB library.

**Comment by kaysievers** [comment]
> Do you know of any 3rd party library that we can use with

I don't think there is at this moment an existing, commonly used library today, which does proper USB support and is extensible to use tinyusb as a transport.

I am personally using this for my own hardware:
https://github.com/versioduo/V2MIDI

**Comment by hathach** [comment]
> > Do you know of any 3rd party library that we can use with
> 
> I don't think there is at this moment an existing, commonly used library today, which does proper USB support and is extensible to use tinyusb as a transport.
> 
> I am personally using this for my own hardware:
> https://github.com/versioduo/V2MIDI

This is a bit troublesome, give me a bit of time. I will peek at how other platforms are doing and decide what to use with midi packet.

**Comment by kaysievers** [comment]
> This is a bit troublesome, give me a bit of time.

I'm pretty confident that someone will port the existing libraries to the packet interface, when it is available.

> I will peek at how other platforms are doing and decide what to use with midi packet.

Other Arduino architectures just re-implemented the API of the Arduino library on top of a packet interface: https://github.com/PaulStoffregen/cores/blob/master/usb_midi/usb_api.h#L13

The serial wire stream format is useful for hardware serial ports, in all other cases it is really not a proper API to provide. Future/upcoming MIDI (2.0) features cannot work with the legacy/mangled packets.

**Comment by kaysievers** [comment]
Just for your information, I've added a second patch on top this:
  https://github.com/versioduo/ArduinoCore-samd/commits/tinyusb-midi-packets

The current MIDI class code corrupts incoming data by overwriting the FIFO and letting the host write faster than the microcontroller can handle it. I need to transfer large blobs (1000+ bytes) with MIDI SysEx in a single transaction.

**Pull request closed without merging**
